defaults: &defaults
  working_directory: /go/src/github.com/goodwithtech/dockle
  docker:
    - image: circleci/golang:1.14
  environment:
    CGO_ENABLED: "0"

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: testing
          command: |
            go test ./...

  release:
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt -y update && sudo apt install -y rpm && curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_release:
    jobs:
    - test:
        filters:
          branches:
            only: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
    - release:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
        requires:
        - test
